apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-brandssource
  annotations:
     kubernetes.io/ingress.class: "gce"
     ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /svcbrands
        backend:
          serviceName: svc-kub-brandssource-service
          servicePort: 8070
      - path: /svcbrands/*
        backend:
          serviceName: svc-kub-brandssource-service
          servicePort: 8070
      - path: /svcbrands/healthz
        backend:
          serviceName: svc-kub-brandssource-service
          servicePort: 8070
      - path: /svcbrands/rediness
        backend:
          serviceName: svc-kub-brandssource-service
          servicePort: 8070

#use annotation rewrite-target to guarantee that traffic redirection starts from root, /.